export const FETCH_LOCATION_DATA = 'FETCH_LOCATION_DATA'
export const FETCH_LOCATION_DATA_SUCCESSFUL = 'FETCH_LOCATION_DATA_SUCCESSFUL'
export const FETCH_LOCATION_DATA_FAILED = 'FETCH_LOCATION_DATA_FAILED'

export const FETCH_TEMPERATURE = 'FETCH_TEMPERATURE'
export const FETCH_TEMPERATURE_SUCCESSFUL = 'FETCH_TEMPERATURE_SUCCESSFUL'
export const FETCH_TEMPERATURE_FAILED = 'FETCH_TEMPERATURE_FAILED'

export const UPDATE_DATA = 'UPDATE_DATA'

export const REFETCH = 'REFETCH'
